name: Flutter Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
      - uses: subosito/flutter-action@v2.16.0
        with:
          channel: 'stable'
      - run: flutter config --no-cli-animations
      - run: flutter pub get
      - run: flutter pub outdated
      # - run: flutter format --set-exit-if-changed .
      - run: flutter analyze .
      # - run: flutter build apk --release
      - run: flutter build apk
      - uses: actions/upload-artifact@v2
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk